services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: doktolib
      POSTGRES_USER: doktolib
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://doktolib:password123@postgres:5432/doktolib
      - DB_SSL_MODE=disable
      - PORT=8080
      - GIN_MODE=debug
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  postgres_data: