services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: doktolib
      POSTGRES_USER: doktolib
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data: