export const specialties = [
  'General Practitioner', 
  'Cardiologist', 
  'Dermatologist', 
  'Gynecologist', 
  'Pediatrician', 
  'Psychiatrist', 
  'Neurologist',
  'Ophthalmologist', 
  'ENT Specialist', 
  'Orthopedist', 
  'Rheumatologist', 
  'Endocrinologist', 
  'Gastroenterologist', 
  'Pulmonologist',
  'Urologist', 
  'Surgeon', 
  'Anesthesiologist', 
  'Radiologist', 
  'Oncologist', 
  'Dentist', 
  'Orthodontist',
  'Oral Surgeon', 
  'Physical Therapist', 
  'Osteopath', 
  'Midwife', 
  'Nurse Practitioner', 
  'Pharmacist',
  'Allergist', 
  'Geriatrician', 
  'Nephrologist', 
  'Hematologist', 
  'Infectious Disease Specialist', 
  'Occupational Medicine',
  'Emergency Medicine', 
  'Critical Care Medicine', 
  'Pathologist', 
  'Forensic Medicine', 
  'Addiction Medicine', 
  'Sexologist'
]

export const cities = [
  'New York, NY', 
  'Los Angeles, CA', 
  'Chicago, IL', 
  'Houston, TX', 
  'Phoenix, AZ', 
  'Philadelphia, PA', 
  'San Antonio, TX', 
  'San Diego, CA',
  'Dallas, TX', 
  'San Jose, CA', 
  'Austin, TX', 
  'Jacksonville, FL', 
  'Fort Worth, TX', 
  'Columbus, OH', 
  'Charlotte, NC', 
  'San Francisco, CA',
  'Indianapolis, IN', 
  'Seattle, WA', 
  'Denver, CO', 
  'Washington, DC', 
  'Boston, MA', 
  'El Paso, TX', 
  'Nashville, TN', 
  'Detroit, MI',
  'Oklahoma City, OK', 
  'Portland, OR', 
  'Las Vegas, NV', 
  'Memphis, TN', 
  'Louisville, KY', 
  'Baltimore, MD', 
  'Milwaukee, WI', 
  'Albuquerque, NM',
  'Tucson, AZ', 
  'Fresno, CA', 
  'Sacramento, CA', 
  'Mesa, AZ', 
  'Kansas City, MO', 
  'Atlanta, GA', 
  'Long Beach, CA', 
  'Colorado Springs, CO',
  'Raleigh, NC', 
  'Miami, FL', 
  'Virginia Beach, VA', 
  'Omaha, NE', 
  'Oakland, CA', 
  'Minneapolis, MN', 
  'Tulsa, OK', 
  'Tampa, FL'
]